### ISSUE TITLE
Config-file must be placed in [win]\System32\-directory

### ISSUE THREAD

**Issue by alfgil** [sorengranfeldt/mare#1]
If I place my 'FIM.MARE.config.xml' file in the [fim]\Extensions Directory with the DLL, I get an error that the dll can not be instantiated. It's OK, I can move the config-file, but the documentation tells me it should be in the same directory as the DLL, or has that changed ??

![fim mare error1](https://user-images.githubusercontent.com/32637207/34669861-b2a9b284-f46b-11e7-9f5f-7025a9b4970a.png)

**Comment by sorengranfeldt** [comment]
Hi

Did you manage to resolve this? I have several installations running where this is not an issue. Could you maybe run DebugView and see what the output is there. That may give you some insights. See more on this here - https://github.com/sorengranfeldt/mare/wiki/Troubleshooting

**Comment by alfgil** [comment]
Unfortunately, the problem is not resolved - actually I now have exactly the same issue in both my Production-environment as in my Test-environment! Your tool is so useful to me, so I can live with this problem, but if you need me for any testing just let me know. I managed to capture debug information from 'DebugView', but the message is basically the same as the eventlog (ref earlier screenshot).

![fim mare error2](https://user-images.githubusercontent.com/32637207/35086001-d9c11c2c-fc22-11e7-854b-876c178e3658.png)

**Comment by sorengranfeldt** [comment]
I'm not really sure whats going on. I have this running with all files in the Extensions folder. Check the filename again and make sure that they match and make sure that the service account can read them and they are not blocked

**Comment by sorengranfeldt** [comment]
Actually, I just checked the code and I think it may have been compiled for Debug and not Release and that may have this effect. I try to release a new version compiled for Release and you can check whether this fixes the problem.

**Comment by sorengranfeldt** [comment]
Could you try this re-release - https://github.com/sorengranfeldt/mare/releases/tag/1.0.1749.26333 and let me know if this fixes the problem?

**Comment by alfgil** [comment]
That fixed the problem! Very good! Before you officially release it, you might want to make sure version numbering inside the DLL is correct. I noticed because it turned out to have a lower(!) version number than before, 1.0.1749.20073, and not the ...26333-number you have used in the text.

**Comment by sorengranfeldt** [comment]
Thank you. I'll probably add a few features within the near future and release a new version
