### ISSUE TITLE
Cannot get MembershipAddWorkflow and MembershipLocked rules to work

### ISSUE THREAD

**Issue by lehtoj** [sorengranfeldt/mare#10]
There's a set of rules I haven't been able to get to work. I am not getting any errors during synchronization either in sync manager, or event log. 

The problem is that no membershipAddWorkflow or membershipLocked attributes appear in any metaverse group objects. Other MARE person and group rules I've created appear to work. The attributes do appear if I set them as constants and skip MARE rules entirely.

What could possibly be the problem with these rules? The membershipAddWorkflow in metaverse is a string, whereas membershipLocked in metaverse is a boolean.

```
        <FlowRule Name="MembershipAddWorkflow" 
            Direction="Import" 
            xsi:type="FlowRule">
            <SourceExpression>
                <Source Name="extensionAttribute1" 
                    xsi:type="Attribute">
                </Source>
            </SourceExpression>
            <Target Name="membershipAddWorkflow" 
                ActionOnNullSource="SetDefault" 
                DefaultValue="None" />
        </FlowRule>

        <FlowRule Name="MembershipLocked" 
            Direction="Import" 
            xsi:type="FlowRule">
            <SourceExpression>
                <Source Name="extensionAttribute2" 
                    xsi:type="Attribute">
                </Source>
            </SourceExpression>
            <Target Name="membershipLocked" 
                ActionOnNullSource="SetDefault" 
                DefaultValue="0" />
        </FlowRule>

        <FlowRule Name="MembershipAddWorkflow" 
            Direction="Export" 
            xsi:type="FlowRule">
            <SourceExpression>
                <Source Name="membershipAddWorkflow" 
                    xsi:type="Attribute">
                </Source>
            </SourceExpression>
            <Target Name="extensionAttribute1" 
                ActionOnNullSource="SetDefault" 
                DefaultValue="None" />
        </FlowRule>

        <FlowRule Name="MembershipLocked" 
            Direction="Export" 
            xsi:type="FlowRule">
            <SourceExpression>
                <Source Name="membershipLocked" 
                    xsi:type="Attribute">
                </Source>
            </SourceExpression>
            <Target Name="extensionAttribute2" 
                ActionOnNullSource="SetDefault" 
                DefaultValue="0" />
        </FlowRule>
```

And here are working MARE rules for groups that I've set.

```
        <FlowRule Name="GroupScope" 
            Direction="Import" 
            xsi:type="FlowRule">
            <SourceExpression>
                <Source Name="groupType" 
                    xsi:type="Attribute" />
            </SourceExpression>
            <Target Name="scope" 
                ActionOnNullSource="Delete">
                <Transforms>
                    <Transform xsi:type="RegexReplace" 
                        Pattern="^(4|\-2147483644)$" 
                        Replacement="DomainLocal" />
                    <Transform xsi:type="RegexReplace" 
                        Pattern="^(2|\-2147483646)$" 
                        Replacement="Global" />
                    <Transform xsi:type="RegexReplace" 
                        Pattern="^(8|\-2147483640)$" 
                        Replacement="Universal" />
                </Transforms>
            </Target>
        </FlowRule>

        <FlowRule Name="GroupType" 
            Direction="Import" 
            xsi:type="FlowRule">
            <SourceExpression>
                <Source Name="groupType" 
                    xsi:type="Attribute" />
            </SourceExpression>
            <Target Name="type" 
                ActionOnNullSource="Delete">
                <Transforms>
                    <Transform xsi:type="RegexReplace" 
                        Pattern="^(\-2147483646|\-2147483644|\-2147483640)$" 
                        Replacement="Security" />
                    <Transform xsi:type="RegexReplace" 
                        Pattern="^(2|4|8)$" 
                        Replacement="Distribution" />
                </Transforms>
            </Target>
        </FlowRule>
```

**Comment by sorengranfeldt** [comment]
What are you trying to do with the first rules? You have no transforms or similar. Should be just direct flows? 

What does the debug log tell you?

**Comment by lehtoj** [comment]
Direct flows aren't used because a default value is needed (hence ActionOnNullSource and DefaultValue), and direct flow does not support flow from AD string attribute to metaverse boolean attribute. Transformation isn't necessary when a value is present.

In regards to the debug log, I'll get back to you later.

**Comment by lehtoj** [comment]
In regards to the debug log. For AD groups that have no value in extensionAttribute1 and extensionAttribute2, the MembershipAddWorkflow and MembershipLocked rules are not triggered at all. There is not a single mention of either rule in the log for such groups.

If I manually set a value to extensionAttribute1 and extensionAttribute2 for an AD group, then the rules are triggered and the values do appear in metaverse.

So in essence, on null source value the rule is skipped. To me, this seems like a bug considering this is the exact scenario ActionOnNullSource and DefaultValue is for, right?

**Comment by sorengranfeldt** [comment]
The fact that no rule is triggered may be a FIM/MIM thing and not a MARE issue. I've seen this happen for nulls values where Advanced Flow Rules are not triggered when the attributes that it depends on doesnt have value. Try adding the "object-id" as a dependency for the flow rule along with the other attributes. That should trigger the rule.

**Comment by lehtoj** [comment]
> Try adding the as a dependency

I think you lost a word there. :) But yes, including another attribute as data source in addition to extensionAttribute1/2 solved the problem. Thank you.

**Comment by sorengranfeldt** [comment]
Great. Glad it helped. Please close the issue if solved.
