### ISSUE TITLE
Externals - in MARE as in MRE

### ISSUE THREAD

**Issue by alfgil** [sorengranfeldt/mare#11]
A while ago you added an "EXTERNAL"-feature in MRE to utilize code already existing in 'MVEXTENSION.DLL' (etc). The same feature would be extremely useful in MARE! We have some very complex ruleextensions already defined in exisiting DLLs, and I would like to continue using them but also being able to add new MARE-defined ruleextensions without interrupting the running solution.

**Comment by sorengranfeldt** [comment]
Though maybe not documented well enough, this is already possible - [see here](https://github.com/sorengranfeldt/mare/wiki/FlowRuleCode) and a sample [here](https://github.com/sorengranfeldt/mare/wiki/Structure-of-the-configuration-file)

**Comment by sorengranfeldt** [comment]
Did this satisfy your needs?

If you feel so, please close the issue 👍

**Comment by alfgil** [comment]
Pretty sure this is what I need! Thanks a lot - again! :-)
