### ISSUE TITLE
Transform Replace on Target

### ISSUE THREAD

**Issue by DKAivazi** [sorengranfeldt/mare#12]
I'm working with FIM.MARE and trying to apply a Transform within a Export FlowRule.

    <FlowRule Name="ExportSchool" Direction="Export" xsi:type="FlowRule">
      <SourceExpression>
        <Source Name="departmentId" xsi:type="Attribute"> D857
          <Transforms>
            <Transform xsi:type="LookupMVValue" LookupAttributeName="id" ExtractValueFromAttribute="locationId" /> L7891
            <Transform xsi:type="LookupMVValue" LookupAttributeName="id" ExtractValueFromAttribute="Code" /> 7891
          </Transforms>
        </Source>
      </SourceExpression>
		<Target Name="School" ActionOnNullSource="Delete" />
			<Transforms>
			  <Transform xsi:type="Replace" OldValue="7891" NewValue="7891E" />
			</Transforms>
		</Target>
    </FlowRule>

I haven't tested the above, but I had the Transform for Replace on the Source instead of the Target and it didn't write a the new Value. My question is does the Replace need a rule above the Replace on whether Code 7891 is True or False, then it will write the new value? Values after # are not in file, just for reference.

Thank you for any insight.

**Comment by sorengranfeldt** [comment]
Is this a complete rule ? There is no Target specified ? Have a look at the samples if you need more insight

**Comment by DKAivazi** [comment]
> Is this a complete rule ? There is no Target specified ? Have a look at the samples if you need more insight

Edited for complete rule

**Comment by sorengranfeldt** [comment]
Also, what does the Debuglog output give you of hints ? You should be able to get more details on whats going on in the log.

**Comment by DKAivazi** [comment]
This ended up working as documented (Samples & Event Viewer). Are Transforms able to distinguish two Replace Transforms with two separate OldValue & NewValue values in the same FlowRule?

**Comment by sorengranfeldt** [comment]
You should be able to make the distinction if I understand. 

For logs, please see documentation also as you are able to use DebugView from Microsoft to see a lot of logging of rules.

If you feel that your question have been answered, please close the issue.

Thanks,
Soren

**Comment by DKAivazi** [comment]
Thank you Soren!
