### ISSUE TITLE
Enhancement Request: Add Word Function

### ISSUE THREAD

**Issue by thomashouston** [sorengranfeldt/mare#14]
Hey Soren,

Any chance of adding the [Word](https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/mim2016-functions-reference#data-retrieval-functions) transform function to MARE?

Many thanks in advance.

Tom

**Comment by sorengranfeldt** [comment]
I can certainly have a look at including that in the next version. I’ll also accept pull requests for that if you have

**Comment by sorengranfeldt** [comment]
I’ll certainly still add this for next version

**Comment by sorengranfeldt** [comment]
Will be added to version 1.2.2625

**Comment by sorengranfeldt** [comment]
Included in [v1.2.2625](https://github.com/sorengranfeldt/mare/releases/tag/1.2.2625)

**Comment by thomashouston** [comment]
Thank you Soren - really appreciate all of your efforts on MRE & MARE.
