### ISSUE TITLE
MultiValueRemoveIfMatch and MultiValueRemoveIfNotMatch are inverted

### ISSUE THREAD

**Issue by antoniopanella** [sorengranfeldt/mare#15]
Dear team, I want remove all attributes from a multivalue attribute that not match a specific Pattern
But I Found that do this are inverted
IF i use  MultiValueRemoveIfNotMatch it remove all values within the pattern   
`<FlowRule Name="employeetype" Direction="Import" xsi:type="FlowRule">
      <SourceExpression>
        <Source Name="ou" xsi:type="MultiValueAttribute">
          <Transforms>
            <Transform xsi:type="MultiValueRemoveIfNotMatch" Pattern="^.*(dipendenti|esterni|registered|alum|studenti).*$" />
            <Transform xsi:type="MultiValueConcatenate" Separator="|" />			
          </Transforms>
        </Source>
      </SourceExpression>
      <Target Name="employeeType" ActionOnNullSource="SetDefault" DefaultValue="n/a" />
    </FlowRule>`

If I use MultiValueRemoveIfMatch it works correct and keep only values in the pattern.

**Comment by ruliane** [comment]
Easy to fix : https://github.com/ruliane/mare/commit/776846051edcfc3ee8e0803926a95007fa973851
