### ISSUE TITLE
Concatenate multiple single-value attributes to a multi-value attribut

### ISSUE THREAD

**Issue by ruliane** [sorengranfeldt/mare#19]
Hi,
In a import flow rule, is there a way to merge values from multiple attributes, into a single multi-value attribute?
I tried something like the following, but source attributes are concatenated into a single string.
```
<FlowRule Name="MyFlowRule" Direction="Import" xsi:type="FlowRule">
  <SourceExpression>
    <Source xsi:type="Attribute" Name="mailAddr1" />
    <Source xsi:type="Attribute" Name="mailAddr2" />
    <Source xsi:type="Attribute" Name="mailAddr3" />
  </SourceExpression>
  <Target Name="mailAddresses" ActionOnNullSource="None" />
</FlowRule>
```

Or should I specify somewhere that `mailAddresses` is a multi-valued attribute?

**Comment by sorengranfeldt** [comment]
Unfortunately not. You'll have to go to code for that. MARE has the option to load your extension DLL for complex rules.

**Comment by ruliane** [comment]
Update: We are currently working on implementing this feature.
