### ISSUE TITLE
Problem with static and multivalue concatenate sources combined in one source expression 

### ISSUE THREAD

**Issue by gvweelden** [sorengranfeldt/mare#2]
I tried to flow a combination of a static value and a concatenate of a multivalue to one attribute in Active Directory.  So it seems the multivalueconcatenate transforms wiped the first static value. Maybe this is a bug?
 
The result of the flowrule below is only the transform value of the second source. The first static value is ignored to the target.
 
<FlowRule Name="description" Direction="Export" xsi:type="FlowRule">
<SourceExpression>
                               <Source Value="Medewerker van " xsi:type="Constant" />
                               <Source Name="AdditionalLocations" xsi:type="MultiValueAttribute">
                                               <Transforms>
                                                               <Transform xsi:type="MultiValueConcatenate" Separator=" " />
                                               </Transforms>
                               </Source>
                </SourceExpression>
<Target Name="description" ActionOnNullSource="Delete" />
</FlowRule>
 
When I change the order of the sources, the flowrule returns both values to the target.. See rule below.
 
<FlowRule Name="description" Direction="Export" xsi:type="FlowRule">
<SourceExpression>
                               <Source Name="AdditionalLocations" xsi:type="MultiValueAttribute">
                                               <Transforms>
                                                               <Transform xsi:type="MultiValueConcatenate" Separator=" " />
                                               </Transforms>
                               </Source>
                               <Source Value=" medewerker" xsi:type="Constant" />
                </SourceExpression>
<Target Name="description" ActionOnNullSource="Delete" />
</FlowRule>

**Comment by sorengranfeldt** [comment]
I'll have a look as soon as possible.

**Comment by sorengranfeldt** [comment]
I had a lookup at your problem and tried to recreate in my lab. I now see that this behaviour is by-design. In your first scenarie, what you are actually trying to do is add a value to a multivalue and that is not supported currently. In your second scenario, you have concatenated the multivalues into a string and then you just 'add' a string to an already existing string.

If you really need to the first scenario supported, I'll have to come out with a new transform or source expression type to support this.

For now, I suggest that you use FlowRuleCode if you want your first scenario working.

Please open another issue and request an enhancement if you would like me to have a look at this.
