### ISSUE TITLE
Create UPN by Concatenating AccountName with domain name

### ISSUE THREAD

**Issue by Regman007** [sorengranfeldt/mare#21]
I am trying the create user principal name by joining the AccountName with a domain name. Example: 
The AccountName is "Jsmith" and the domain "domain1.com"
the result should be "Jsmith@domain1.com"

How can I achieve that? 
Thanks

**Comment by sorengranfeldt** [comment]
Have a look at the different samples - but basically, you would just add more source expressions and the different values would be concatenated, i.e.

```xml
<SourceExpression>
  <Source Name="Domain" xsi:type="Attribute">
    <Transforms>
      <Transform xsi:type="ToLower"/>
    </Transforms>
  </Source>
  <Source Value=" @" xsi:type="Constant"/>
  <Source Name="AccountName" xsi:type="Attribute"/>
</SourceExpression>
```

**Comment by sorengranfeldt** [comment]
Marking as resolved since no reply

**Comment by Regman007** [comment]
Thank you Soren for the solution. it worked.
