### ISSUE TITLE
MARE external deprovision

### ISSUE THREAD

**Issue by EminaKaric** [sorengranfeldt/mare#22]
Hi Søren!
We’re using MARE with an external DLL, which seems to be working fine. However we’ve now had the need arise to use rule extensions for deprovision actions and got a strange error. The wiki page says deprovision is coming in a later version but, that of course hasn’t been updated in a while. 

I’ll probably dig into the code myself as well but you might already have an idea.

**Comment by sorengranfeldt** [comment]
You’re correct. It’s not been implemented yet. You should be able to pretty much code the code from the region FlowRuleCode in the Import/ Export function to the deprovision implementation. 

If you do, I would accept a pull request if it works. 

Unfortunately, I don’t have time to code this for free at the moment but I can review pull request and merge

**Comment by ruliane** [comment]
Hi @EminaKaric ,
FYI, I [implemented a deprovisionning](https://github.com/ruliane/mare/wiki#deprovisionning) process in FIM.MARE.
It's still a work in progress and has not been tested thoroughly, but for what I know, it does work.

**Comment by EminaKaric** [comment]
Thanks, I'll check it out.

**Comment by alfgil** [comment]
We (Lovisenberg Hospital, Oslo, Norway) are using the "EminaKaric-version" of MARE and it is working flawlessly in our environment. I would hope her enhancements woud make it become part of the standard product.

**Comment by sorengranfeldt** [comment]
I’ll have to look into this. Not sure if there is a pull request yet. But I can accept a working pull request with accompanying documentation

**Comment by sorengranfeldt** [comment]
Still planning to merge

**Comment by sorengranfeldt** [comment]
Merged and published
