### ISSUE TITLE
Rules path and descriptions

### ISSUE THREAD

**Issue by lehtoj** [sorengranfeldt/mare#7]
First of, thank you very much for making MRE and MARE.

I would however really like if MARE would be a bit more like MRE in some regards.

- Ability to choose where rules are located, like in MRE. I like to keep my rules in a separate data directory in non-system partition.
- Ability to give rules and conditions descriptions. Without descriptions colleagues may not be entirely sure of exact purpose of a rule. Not without reading documentation at least, and we all write docs, right?
- Ability to enable/disable individual rules in a file.

**Comment by sorengranfeldt** [comment]
I'll have a look into this and consider it for the next release. With the current version, you should be able to add a, i.e. Description tag and MARE will ignore that.

**Comment by sorengranfeldt** [comment]
Is this still an issue ?

**Comment by lehtoj** [comment]
I no longer work with MIM, and as such I can no longer confirm whether or not an issue is still valid. But since there hasn't been a MARE release that addresses these issues (according to release changelog), I would guess yes. I got around the first problem  by creating a symlink.
