### ISSUE TITLE
Group type transform in a single flow rule?

### ISSUE THREAD

**Issue by lehtoj** [sorengranfeldt/mare#8]
Hello.

AD defines group scope and type in one attribute; groupType. 

Security and Distribution types have three values each. This is quite simple to achieve with a RegexIsMatch transform.

`<Transform xsi:type="RegexIsMatch" Pattern="^(2|4|8)$" TrueValue="Distribution" FalseValue="Security" />`

But I hit a wall trying to figure out how to transform the six possible values into three types; DomainLocal, Global and Universal. The only way I could think of is to make multiple flow rules with a SourceValueMatch condition. Surely this should be achievable in a single rule?

**Comment by sorengranfeldt** [comment]
You can chain Transforms and use RegexReplace to maybe get to your desired result. Have a look at the 'Check if user is active' sample in the Wiki under [Sample rules](https://github.com/sorengranfeldt/mare/wiki/sample-rules)

**Comment by lehtoj** [comment]
Oh yeah. I figured it out sometime after I posted this issue. The below works.

```
<Transform xsi:type="RegexReplace" Pattern="^(4|\-2147483644)$" Replacement="DomainLocal" />
<Transform xsi:type="RegexReplace" Pattern="^(2|\-2147483646)$" Replacement="Global" />
<Transform xsi:type="RegexReplace" Pattern="^(8|\-2147483640)$" Replacement="Universal" />
```

**Comment by sorengranfeldt** [comment]
Great. Can the issue be closed then?

**Comment by lehtoj** [comment]
Yes it can. Sorry for the noise. :)
