### ISSUE TITLE
AccountExpires Export

### ISSUE THREAD

**Issue by Schliefer86** [sorengranfeldt/mare#9]
Hi Søren
I’m using your cool FIM.MARE in an Customer Project and we are searching for a Solution to Export the Active Directory AccountExpires Attribute.
I tried to use the Importing Rule as a Sample to Export the EmployeeEndDate to the AccountExpires Attribute in Active Directory but without Success.
I'm not sure if I just did it wrong or if this is not possible at the moment. If it is not possible at the moment, is there a possibility that this will be implemented in a next release?
KR Mario Bader

**Comment by sorengranfeldt** [comment]
Could you please post the Export rule that isn’t working currently?

**Comment by Schliefer86** [comment]
Hi
at the moment I'm using the following rule
--------------------------
<FlowRule Name="accountExpires" Direction="Export" xsi:type="FlowRule">
			<SourceExpression>
				<Source Name="accountExpires" xsi:type="Attribute">
					<Transforms>
						<Transform xsi:type="FormatDate" DateType="FileTimeUTC" ToFormat="yyyy-MM-ddTHH:mm:ss.000"/>
					</Transforms>
				</Source>
			</SourceExpression>
			<Target Name="accountExpires" ActionOnNullSource="Delete" />
		</FlowRule>
--------------

**Comment by Schliefer86** [comment]
at the moment i'm using the expression in the attachment
[AccountExpiresExpression.txt](https://github.com/sorengranfeldt/mare/files/2653623/AccountExpiresExpression.txt)

**Comment by sorengranfeldt** [comment]
Seems like you're trying to write a date to accountExpires in AD. You should convert FROM a date to FileTimeUTC as I think that is what AD except you to write in that attribute. See this example - https://social.technet.microsoft.com/Forums/en-US/81f8a0cd-f41b-45ba-afb8-f66ca1aef065/setting-accountexpires-attribute-in-ad?forum=identitylifecyclemanager

**Comment by Schliefer86** [comment]
you are right, but the question: does the MARE actually support these or should we implement an additional Rule Extension? KR Mario

**Comment by sorengranfeldt** [comment]
It should be supported though not directly tested.

**Comment by Schliefer86** [comment]
I have tested several settings but it is working only for the import. 
I have now added a new transform function to the MARE in my Solution, because actually in my point of view the FIM MARE is not supporting exporting an FileTimeUTC Integer Value with existing functions.
You can find all relevant changes in the Attachments.

[TransformToFileTimeUTC.zip](https://github.com/sorengranfeldt/mare/files/2727500/TransformToFileTimeUTC.zip)

It would be greate if you could Integrate these changes in your solution.
KR Mario

**Comment by sorengranfeldt** [comment]
I'll have a look to incorporate and check for next version. Otherwise, you could to a pull and merge request if you want to.

**Comment by sorengranfeldt** [comment]
Fixed: Included in [release 1.2.2612](https://github.com/sorengranfeldt/mare/releases/tag/FIM.MARE.1.2.2612)
